### ISSUE TITLE
Exception when running TLC

### ISSUE THREAD

**Issue by agentultra** [pmer/tla-bin#1]
Hey, working on some tooling/automation for my TLA+ workflow!

Super grateful for finding this repo. You might chalk this up to my ignorance with Java but when I run the wrappers I get this error (traceback elided):

```
TLC2 Version 2.13 of 18 July 2018
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at tlc2.TLC.main(TLC.java:210)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
```

```
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by pmer** [comment]
Glad to hear that you were able to keep tracing this issue. Yeah, TLA+ has a few rough corners with what it wants from your Java installation. Good luck—hope you get it working!

**Comment by pmer** [comment]
Looks like upstream has now fixed the issue. https://github.com/tlaplus/tlaplus/issues/176
