### ISSUE TITLE
tlatex error

### ISSUE THREAD

**Issue by KevinTung** [pmer/tla-bin#10]
When running `tlatex example.tla`, got 
`
Exception in thread "main" tla2tex.TLA2TexException: TLATeX unrecoverable error: -- Trying to run the command `latex example.tex' produced the following error
    Cannot run program "latex": error=2, No such file or directory.
	at tla2tex.Debug.ReportError(Debug.java:26)
	at tla2tex.ExecuteCommand.executeCommand(ExecuteCommand.java:34)
	at tla2tex.LaTeXOutput.RunLaTeX(LaTeXOutput.java:483)
	at tla2tex.TLA.runTranslation(TLA.java:246)
	at tla2tex.TLA.main(TLA.java:150)
`

**Comment by pmer** [comment]
Hi, thanks for this report. This error can occur when one does not have LaTeX installed on the machine running `tlaltex`.

Do you have LaTeX installed?
